package nc.univ.java.model;

public enum FormationEnum {
    LICENCE_INFORMATIQUE,
    LICENCE_SVT,
    LICENCE_MATH,
    LICENCE_PHYSIQUE_CHIMIE,
    LICENCE_DROIT,
    LICENCE_LETTRES,
    LICENCE_ANGLAIS,
    LICENCE_ECO_GESTION,
    LICENCE_HISTOIRE
}
